### ISSUE TITLE
openplatform docker compose 

### ISSUE THREAD

**Issue by yilativ** [totaljs/openplatform#73]
Hi, so I got done with the openplatform set up as it is in readme. 

Then I added this to the docker compose file:
```YAML
version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=total
      - POSTGRES_PASSWORD=platform
      - POSTGRES_DB=openplatform
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "total", "-d", "openplatform"]
      interval: 3s
      timeout: 3s
      retries: 5

  openplatform:
    container_name: openplatform
    image: totalplatform/openplatform:latest
    ports:
      - 8100:8000
    volumes:
      - openplatform:/www/databases/
    environment:
      - DATABASE=postgresql://total:platform@postgres:5432/openplatform
    depends_on:
      postgres:
        condition: service_healthy
  
  uistudio: 
    container_name: uistudio
    image: totalplatform/uistudio:latest
    ports:
      - 8101:8000
  
  flow: 
    container_name: flow
    image: totalplatform/flow:latest
    ports:
      - 8102:8000

volumes:
  pgdata:
    driver: local
  openplatform:
    driver: local
```

Individually they work when I use host.docker.internal:<<port>>. 

However, when I import into the openplatform, using for example their domain names that would be available to openplatform: 
`http://flow:8102/openplatform.json`. It imports, but then when I try to use the app, it's just 403. 

I don't know how to gain access after that and the openplatform home or app screen really give me indication on how to access it. 
How do I get back into the imported app?
